#coding:utf-8

class Constant:

    DATA_DICTIONARY_KEY_CERTAINTY = "certainty"
    DATA_DICTIONARY_KEY_DATETIME = "datetime"
    DATA_DICTIONARY_KEY_VALUE = "value"

    DATETIME_STRING_KEY_FORMAT = "%Y/%m/%d-%H:%M:%S"

    INSTANT_DICTIONARY_KEY_CERTAINTY = "certainty"
    INSTANT_DICTIONARY_KEY_VALUE = "value"

    POINTS_IN_GRAPHICS_IDEAL = 1000
    POINTS_IN_GRAPHICS_MAX = 1500
    POINTS_IN_GRAPHICS_MIN = 500


class SystemError:

    GET_CONSUMER_UNIT_ELECTRICAL_PARAMETER_DATA_CLUSTERED_ERROR =\
        "GET_CONSUMER_UNIT_ELECTRICAL_PARAMETER_DATA_CLUSTERED_ERROR"

    GET_DATA_CLUSTERS_LIST_ERROR = "GET_DATA_CLUSTERS_LIST_ERROR"
    GET_INSTANT_DELTA_FROM_TIMEDELTA_ERROR =\
        "GET_INSTANT_DELTA_FROM_TIMEDELTA_ERROR"

    GET_NORMALIZED_REQUEST_DATA_LIST_ERROR =\
        "GET_NORMALIZED_REQUEST_DATA_LIST_ERROR"

    GET_TIMEDELTA_FROM_NORMALIZED_REQUEST_DATA_LIST_ERROR =\
        "GET_TIMEDELTA_FROM_NORMALIZED_REQUEST_DATA_LIST_ERROR"

    RENDER_INSTANT_MEASUREMENTS_ERROR = "RENDER_INSTANT_MEASUREMENTS_ERROR"
