from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'rbac.views.control_panel'),
                       url(r'^add_permissions/',
                           'rbac.views.add_data_context_permissions'),

                       url(r'^nuevo_rol/', 'rbac.views.add_role'),
                       url(r'^editar_rol/(?P<id_role>\d+)/',
                           'rbac.views.edit_role'),
                       url(r'^delete_perms/(?P<id_role>\d+)',
                           'rbac.views.edit_role'),
                       url(r'^ver_rol/(?P<id_role>\d+)', 'rbac.views.see_role'),
                       url(r'^eliminar_rol/(?P<id_role>\d+)',
                           'rbac.views.delete_role'),
                       url(r'^delete_batch/$', 'rbac.views.delete_batch'),
                       url(r'^add_user/$', 'rbac.views.add_user'),
                       url(r'^eliminar_usuario/(?P<id_user>\d+)',
                           'rbac.views.delete_user'),
                       url(r'^delete_batch_user/$',
                           'rbac.views.delete_batch_user'),
                       url(r'^editar_usuario/(?P<id_user>\d+)/',
                           'rbac.views.edit_user'),
                       url(r'^ver_usuario/(?P<id_user>\d+)',
                           'rbac.views.see_user'),
                       url(r'^roles/', 'rbac.views.view_roles'),
                       url(r'^user_role_status/(?P<id_ur>\d+)/',
                           'rbac.views.switch_status_user_role'),
                       url(r'^delete_user_role/(?P<id_ur>\d+)/',
                           'rbac.views.delete_user_role'),
                       url(r'^status_batch_user_role/$',
                           'rbac.views.status_batch_user_role'),
                       url(r'^asign_role/(?P<id_role>\d+)/',
                           'rbac.views.asign_role'),
                       url(r'^usuarios/', 'rbac.views.view_users'),
                       url(r'^asignar_roles/',
                           'rbac.views.add_data_context_permissions'),
                       url(r'^roles_asignados/',
                           'rbac.views.added_data_context_permissions'),
                       url(
                           r'^eliminar_asignacion_rol/(?P<id_data_context>\d+)/',
                           'rbac.views.delete_data_context'),
                       url(r'^delete_batch_datacontext/$',
                           'rbac.views.delete_batch_data_context'),


                       url(r'^search_users/', 'rbac.views.search_users'),
                       url(r'^get_group/(?P<id_operation>\d+)',
                           'rbac.views.get_select_group'),
                       url(r'^get_object/(?P<id_group>\d+)',
                           'rbac.views.get_select_object'),

                       url(r'^add_user_pop/', 'rbac.views.add_user_pop'),
                       url(r'^save_user_pop/', 'rbac.views.add_user_pop'),
)